### ISSUE TITLE
Handbook - Create Baseline Handbook

### ISSUE THREAD

**Issue by ChadABratton** [cagov/handbook-cadotgov#1]
- [x] Create landing page for handbook
- [x] create new markdown pages where more information is needed about specific subjects
- [x] upload existing documentation from Google Drive - Shared Alpha Drive

**Comment by lukefretwell** [comment]
As a team member of Alpha.CA.gov, I would like to have a memorable domain, so I can easily access the Alpha.CA.gov handbook.

Example: handbook.alpha.ca.gov
