### ISSUE TITLE
DNS for hanbdbook

### ISSUE THREAD

**Issue by ChadABratton** [cagov/handbook-cadotgov#11]
From Readthedocs documentation:
https://docs.readthedocs.io/en/stable/custom_domains.html

Custom Domain Support
You can also host your documentation from your own domain by adding a domain to your project:

Add a CNAME record in your DNS that points the domain to: readthedocs.io
Add a project domain in the Domains project admin page for your project.

**Comment by ChadABratton** [comment]
I believe we need a DNS record that points handbook.alpha.ca.gov to readthedocs.io per documentation linked above.

**Comment by abquirarte** [comment]
ready to close? @ChadABratton

**Comment by KimberlyglennTSM** [comment]
Received confirmation from Chad that the DNS has been setup for the Handbook.
