### ISSUE TITLE
Organizational Headers

### ISSUE THREAD

**Issue by jpetrucione** [cagov/handbook-cadotgov#13]
Suggest adjusting the organization so that "Welcome" and "Employee Resources and Guidelines" are separate primary Headers. 

Need to move "Website Architecture" out of "Welcome" (where to, not sure)

Updated left hand navigation wld include:
Welcome
Employee Resources and Guidelines 
Planning
Principles
Assets

**Comment by lukefretwell** [comment]
@jpetrucione add this to the Google doc and close?
