### ISSUE TITLE
Welcome Copy

### ISSUE THREAD

**Issue by jpetrucione** [cagov/handbook-cadotgov#14]
We need to include copy in the Welcome section that explains what the handbook is/who we are.  

DRAFT COPY
The Alpha.CA.gov team is working to make it easier for Californians to access, understand and use digital information and services. This handbook is a product of that work. 

This handbook is an iterative, practical and accessible tool. Our team uses it to record and reference our ways of work, principles and guidelines.

For anyone else visiting this page, we offer this handbook as a resource.

**Comment by lukefretwell** [comment]
Done: https://handbook.alpha.ca.gov/en/latest/
