### ISSUE TITLE
Handbook - custom domain

### ISSUE THREAD

**Issue by ChadABratton** [cagov/handbook-cadotgov#16]
Replace existing handbook url https://handbook-cadotgov.readthedocs.io/en/latest/ with custom domain handbook.alpha.ca.gov

- [x] submit dns request to map handbook.alpha.ca.gov to readthedocs.io
- [x] add the custom domain to the readthedocs admin seciton
- [x] enforce http > https redirect

**Comment by abquirarte** [comment]
https now enforced? @carterm @ChadABratton

**Comment by davisopendataguy** [comment]
Good question. One for Manveer or Pam.

Sent from my iPhone

On Dec 16, 2019, at 3:37 PM, abquirarte <notifications@github.com> wrote:

﻿

https now enforced? @carterm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarterm&data=02%7C01%7Cstuart.drown%40govops.ca.gov%7C4e3c623cb59c450f12cd08d78280f9d2%7C68a88534151d4e79804609be7890656c%7C0%7C1%7C637121362784643210&sdata=J2F9fPKo3egJiHQAGtq9B7ZUS60UmTRQbwLCgKKij7s%3D&reserved=0> @ChadABratton<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChadABratton&data=02%7C01%7Cstuart.drown%40govops.ca.gov%7C4e3c623cb59c450f12cd08d78280f9d2%7C68a88534151d4e79804609be7890656c%7C0%7C1%7C637121362784653205&sdata=V4BRXS7arnHC3Lo0VSj%2F1lRC6HF7Z1kUvdk2YNAfZzA%3D&reserved=0>

**Comment by abquirarte** [comment]
This is for the Alpha, not Code California :)
But on that note- we still need those repositories transferred over to OET.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davisopendataguy** [comment]
Still don’t know the answer then.  What is the question?

Sent from my iPhone

On Dec 16, 2019, at 9:31 PM, abquirarte <notifications@github.com> wrote:

﻿This is for the Alpha, not Code California :)
But on that note- we still need those repositories transferred over to OET.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abquirarte** [comment]
Lol. I'll give you a call!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davisopendataguy** [comment]
I’m in Davis for an appointment.   I’ll be in any 11.

Sent from my iPhone

On Dec 17, 2019, at 8:26 AM, abquirarte <notifications@github.com> wrote:

﻿Lol. I'll give you a call!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abquirarte** [comment]
Sounds good! Thanks Stu. :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
