### ISSUE TITLE
Add content guidelines/style guide

### ISSUE THREAD

**Issue by lukefretwell** [cagov/handbook-cadotgov#18]
I a designer/content provider for Alpha.CA.gov, I would like guidance on content style so I can make sure I'm following proper content strategy and protocol.

Reference: 

* https://content-guide.18f.gov/
* https://content-guide.18f.gov/style-guides/

General recommendation: Wherever Alpha.CA.gov is spelled out, it should be linked.

**Comment by humancenteredhuman** [comment]
Created a minimum viable [Content Guide](https://docs.google.com/document/d/1YsOO9GL5MXlkVTZ4JQHFefdRwPRgTe_ACNNRsGjs1LI/edit)

Yes on Alpha.ca.gov should be linked.

**Comment by ChadABratton** [comment]
@lukefretwell  Are we okay to close this story?
@abquirarte  @KimberlyglennTSM  I think we are good, but not sure if Luke is happy yet.

**Comment by abquirarte** [comment]
Ready to close. Refer to content Guide
