### ISSUE TITLE
Add Google Analytics to Handbook

### ISSUE THREAD

**Issue by lukefretwell** [cagov/handbook-cadotgov#19]
Reference: https://docs.readthedocs.io/en/stable/guides/google-analytics.html

cc @ChadABratton @carterm

**Comment by abquirarte** [comment]
is this ready for review/done? @ChadABratton

**Comment by ChadABratton** [comment]
I have just completed this now, thanks @carterm  for giving me the ID

**Comment by abquirarte** [comment]
thank you @ChadABratton and @carterm ! Closing this issue.
