### ISSUE TITLE
Add product framing content to handbook 

### ISSUE THREAD

**Issue by abquirarte** [cagov/handbook-cadotgov#23]
Document here: 
https://docs.google.com/document/d/1_yB9t608T-oIU3FO85NdHLqbnaIOx6ADJS6cPvPSzlE/edit#

**Comment by abquirarte** [comment]
I took a stab at this. May have to be cleaned-up/ organized. 
https://github.com/cagov/handbook-cadotgov/blob/master/docs/ProductFraming.md 

CC: @ChadABratton and @KimberlyglennTSM

**Comment by lukefretwell** [comment]
Added here: https://handbook.alpha.ca.gov/en/latest/principles/#product-framing
