### ISSUE TITLE
Add content style guide to handbook

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/handbook-cadotgov#25]
Document: https://docs.google.com/document/d/1YsOO9GL5MXlkVTZ4JQHFefdRwPRgTe_ACNNRsGjs1LI/edit

**Comment by lukefretwell** [comment]
Needs cleaned up but good start. There's a build fail that I'm filing an issue for. 

https://readthedocs.org/projects/handbook-cadotgov/builds/10302660/
