### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by lukefretwell** [cagov/handbook-cadotgov#27]
**Describe the bug**

@ChadABratton @aaronhans could you take a look at this? I'm getting a build fail when trying to push updates.

Build #10302660: https://readthedocs.org/projects/handbook-cadotgov/builds/10302660/

cc @jpetrucione @KimberlyglennTSM @abquirarte

**Comment by ChadABratton** [comment]
@lukefretwell  I took a look and have not been able to fix yet. I see the mkdocs.yml file looks just fine. Do you know if there were any other major changes yesterday that could be causing the issue with builds? It could be an issue with readthedocs but I am not sure yet.

**Comment by lukefretwell** [comment]
@ChadABratton per recommendations from RTD:

https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

cc @abquirarte
